apiVersion: apps/v1
kind: Deployment
metadata: 
  name: accounts-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounts
  template:
    metadata:
      labels:
        app: accounts
    spec:
      containers:
        - name: accounts
          image: eolnexus/accounts
          env: 
            - name: MONGO_URI
              value: 'mongodb://accounts-mongo-srv:27017/accounts'
            - name: JWT_KEY
              valueFrom: 
                secretKeyRef: 
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: accounts-srv
spec:
  selector:
    app: accounts
  ports:
    - name: accounts
      protocol: TCP
      port: 5000
      targetPort: 5000