apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations: 
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    - host: nexuseol.com
      http:
        paths:
          - path: auth/?(.*)
            pathType: Prefix
            backend:
              service:
                name: auth-srv
                port:
                  number: 5000
          - path: accounts/?(.*)
            pathType: Prefix
            backend:
              service:
                name: accounts-srv
                port:
                  number: 5000
          - path: products/?(.*)
            pathType: Prefix
            backend:
              service:
                name: products-srv
                port:
                  number: 5000
          - path: users/?(.*)
            pathType: Prefix
            backend:
              service:
                name: users-srv
                port:
                  number: 5000
          - path: tests/?(.*)
            pathType: Prefix
            backend:
              service:
                name: tests-srv
                port:
                  number: 5000
          - path: testattempts/?(.*)
            pathType: Prefix
            backend:
              service:
                name: tests-srv
                port:
                  number: 5000
          - path: testresults/?(.*)
            pathType: Prefix
            backend:
              service:
                name: tests-srv
                port:
                  number: 5000
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: client-srv
                port:
                  number: 5000