apiVersion: apps/v1
kind: Deployment
metadata: 
  name: tests-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tests
  template:
    metadata:
      labels:
        app: tests
    spec:
      containers:
        - name: tests
          image: eolnexus/tests
          env: 
            - name: MONGO_URI
              value: 'mongodb://tests-mongo-srv:27017/tests'
            - name: JWT_KEY
              valueFrom: 
                secretKeyRef: 
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: tests-srv
spec:
  selector:
    app: tests
  ports:
    - name: tests
      protocol: TCP
      port: 5000
      targetPort: 5000